# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c38e7d50d00579f18da0bee1504ec47566d30354f5427d99834d4f6a2bbcab60ba6e113fd3284370cfeb745a36fb28be81973d5baa0fae2c995aedff8670b652

test:
  secret_key_base: fa5bc771c38b6228b076c9e0f6758d9748216185b53fdb3071e59a3444992c751fc65433731faec648ee25053cc49e4f9ce01a0c0f70fae56cf9c1fcfaf19536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
